var sampleInfo1 = {name: 'The "Boss" Puzzle',
  leadImage: 'images/lead_image.png',
  slides: [
  {url: 'images/image1.jpg',
  headline: 'The 15 Puzzle',
  description: "This cartoon about the 1880 presidential primary references a newly-invented game called a sliding puzzle. \n\nThe object of the sliding puzzle was to negotiate a block into the bottom right corner, and here politicians are vying to reach that 'winning' position."},
  {url: 'images/image2.jpg',
  headline: 'Roscoe Conkling',
  description: "The cartoon's central figure is New York political boss Roscoe Conkling. \n\nConkling is puzzling over how to move his favored candidate Ulysses S. Grant into the presidency. A Grant nomination would likely mean more power for Conkling."},
  {url: 'images/image3.jpg',
  headline: 'James G. Blaine',
  description: "Conkling's hand rests on James G. Blaine, a contender of a candidate, who he hated. \n\nA respected and well-liked Republican Party elder, Blaine had almost become president in 1876, but Conkling had helped sabotaged him.\n\nFour years later, Blaine was considered a frontrunner, which is likely why he's places him so close to the 'winning' slot in cartoon."},
  {url: 'images/image4.jpg',
  headline: 'Ulysses S. Grant',
  description: "Conkling's preferred candidate was Ulysses S. Grant, who had already been president twice and was trying for a third term. The arrogance of the move was controversial."},
  {url: 'images/image5.jpg',
  headline: 'Samuel Tilden',
  description: "A Democrat from the swing state of New York, Tilden nearly became President in 1876, losing in a compromise that many saw as a corrupt deal. He was considered the favorite to run again in 1880, which is probably why he's depicted one square away from the 'winning' spot in the bottom right corner. Tilden didn't end up running."},
  {url: 'images/image6.jpg',
  headline: 'Benjamin Butler',
  description: "Butler had supporters across the political spectrum—he was often said to be 'a member of all parties and false to each'—and was considered a presidential possibility when the Greenbackers convened in Chicago in 1880."},
  {url: 'images/image7.jpg',
  headline: 'Thomas F. Bayard',
  description: "Bayard was a Conservative Delaware Democratic with a strong record of supporting the Southern States (he thought they should be able to seceded peacefully). He was a contendor for the 1880 nomination, and ended up finishing second."},
  {url: 'images/image8.jpg',
  headline: 'John Sherman',
  description: "A Treasury Secretary with solid economic credentials, John Sherman was also so cold and lacking in charisma that he was known as the icicle. Three months after this cartoon was published, James Garfield got up to nominate 'the icicle' at the contested GOP convention. Garfield's rousing speech barely mentioned Sherman, and it was Garield, not Sherman, who got the nomination and became President. Little wonder Sherman is so far from the winning bottom-right slot in this cartoon."}
]}

var sampleInfo2 = {
  name: 'The Protectors of our Industries',
  leadImage: 'images/raft.jpg',
  slides: [
  {url: 'images/raft-figure1.jpg',
  headline: 'Water',
  description: "The figures in this cartoon float on an ocean referred to as hard times."},
  {url: 'images/raft-figure2.jpg',
  headline: 'Workers',
  description: "A collection of working class laborers stand in the ocean beaten down by the burden on their shoulders."},
  {url: 'images/raft-figure3.jpg',
  headline: 'Industry',
  description: "They carry on their shoulders the industries that depend upon their labor. The cartoon represents the major industries of the day, along with the average wages its workers make. Included here are lumber... "},
  {url: 'images/raft-figure4.jpg',
  headline: 'The Robber Barons',
  description: "Resting comfortably on top of the industries and the laborers lifting them high above the high times are the country's most famous Robber Barons, who are cushioned by enormous bags of money."},
  {url: 'images/raft-figure6.jpg',
  headline: 'Gould',
  description: "Jay Gould"},
  {url: 'images/raft-figure7.jpg',
  headline: 'Vanderbilt',
  description: "Cornelius Vanderbilt."}
]}
